version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: myapp-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: myapp-frontend:latest
    ports:
      
      - "80:80"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_APP_BACKEND_URL=http://backend:5000

    command: npm run web
