# Use an official Node.js runtime as a base image
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install Expo CLI globally
RUN npm install -g expo-cli

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

EXPOSE 19006

# Start the application
CMD ["npm", "start"]
